# Generated by Django 5.0.3 on 2024-12-02 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_id', models.CharField(default='', max_length=200, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('name_en', models.CharField(default='', max_length=200, null=True)),
                ('name_hy', models.CharField(default='', max_length=200, null=True)),
                ('parent_name', models.CharField(default='', max_length=200)),
                ('parent_name_en', models.CharField(default='', max_length=200, null=True)),
                ('parent_name_hy', models.CharField(default='', max_length=200, null=True)),
                ('latitude', models.DecimalField(decimal_places=15, default=0.0, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, default=0.0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_hy', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200)),
                ('position_en', models.CharField(max_length=200, null=True)),
                ('position_hy', models.CharField(max_length=200, null=True)),
                ('github_link', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team')),
            ],
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('coordinates', models.CharField(default='0.0, 0.0', help_text='Latitude, Longitude (e.g., 40.7128, -74.0060)', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
