# Generated by Django 4.2.4 on 2023-08-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_homepage_delete_page_alter_devicedetails_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='par1',
            new_name='paragraph_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='par2',
            new_name='paragraph_2',
        ),
    ]
