# Generated by Django 4.2.4 on 2023-08-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_region_contactmessage_phone_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='title',
            new_name='title_1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_2',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
