# Generated by Django 4.2.5 on 2023-09-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_contactmessage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Armenia', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('light', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pm1', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('atmospheric_pm1', models.FloatField()),
                ('atmospheric_pm2_5', models.FloatField()),
                ('atmospheric_pm10', models.FloatField()),
                ('co2', models.FloatField()),
                ('speed', models.FloatField()),
                ('rain', models.FloatField()),
                ('direction', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.devices')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.RemoveField(
            model_name='station',
            name='device_detail',
        ),
        migrations.RemoveField(
            model_name='station',
            name='region',
        ),
        migrations.DeleteModel(
            name='DeviceDetails',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
