# Generated by Django 4.2.5 on 2023-09-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_devices_weatherdata_delete_contactmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='atmospheric_pm1',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='atmospheric_pm10',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='atmospheric_pm2_5',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='device',
        ),
    ]
