# Generated by Django 4.2.5 on 2023-10-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_about_contactus_footer_delete_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='devicedetail',
            name='device_number',
        ),
        migrations.AddField(
            model_name='devicedetail',
            name='name',
            field=models.CharField(default=1213, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicedetail',
            name='parent_name',
            field=models.CharField(default=56, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
