# Generated by Django 4.2.5 on 2023-10-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_devicedetail_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetail',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='devicedetail',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
