# Generated by Django 4.2.5 on 2023-10-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_devicedetail_device_number_alter_devicedetail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedetail',
            old_name='device_number',
            new_name='device_id',
        ),
    ]
