# Generated by Django 4.2.6 on 2023-10-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_devicedetail_device_number_alter_devicedetail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedetail',
            name='device_number',
        ),
        migrations.AddField(
            model_name='devicedetail',
            name='gererated_id',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
