# Generated by Django 4.2.5 on 2023-10-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rename_device_number_devicedetail_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedetail',
            name='device_id',
        ),
        migrations.AddField(
            model_name='devicedetail',
            name='device_number',
            field=models.CharField(default=34, max_length=50),
            preserve_default=False,
        ),
    ]
