# Generated by Django 4.2.6 on 2023-10-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_devicedetail_device_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedetail',
            name='gererated_id',
        ),
        migrations.AddField(
            model_name='devicedetail',
            name='generated_id',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
