# Generated by Django 4.2.5 on 2023-10-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_devicedetail_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedetail',
            name='device_number',
        ),
    ]
