# Generated by Django 4.2.6 on 2023-10-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_devicedetail_gererated_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetail',
            name='generated_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
