POST  http://127.0.0.1:8000/api/users/submit-form/ 
Content-Type: application/json

{
"name": "Arno", "email": "rnobaboomian@gmail.com", "message": "Hello, this is a test message.", "coordinates": "40.7128, -74.0060"
}