# actions.yaml
name: Deploy on push staging actions

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

runs:
  using: "composite"
  steps:
    - name: Set up SSH connection
      env:
        HOSTNAME: ${{ inputs.hostname }}
        USERNAME: ${{ inputs.username }}
        SSH_KEY: ${{ inputs.ssh_key }}
      run: |
        echo "$SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -i ssh_key.pem $USERNAME@$HOSTNAME
