# actions.yaml
name: Deploy on push staging actions

on:
  push:
    branches:
      - staging

inputs:
  hostname:
    description: 'Hostname of the server.'
    required: true
  username:
    description: 'Username for SSH authentication.'
    required: true
  ssh_key:
    description: 'SSH private key for authentication.'
    required: true


jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Set up SSH connection
      env:
        HOSTNAME: ${{ inputs.hostname }}
        USERNAME: ${{ inputs.username }}
        SSH_KEY: ${{ inputs.ssh_key }}
      run: |
        echo "$SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -i ssh_key.pem $USERNAME@$HOSTNAME
