on:
  push:
    branches:
      - main

name: Deploy on push

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
          - name: Deploy in EC2
            env:
                PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
                HOSTNAME : ${{ secrets.EC2_IP  }}
                USER_NAME : ${{ secrets.EC2_USERNAME  }}


            run: |
              echo "${{ env.PRIVATE_KEY }}" > private_key.pem && \
                 chmod 600 private_key.pem
              ssh -o StrictHostKeyChecking=no -i private_key.pem \
                 ${{ env.USER_NAME }}@${{ env.HOSTNAME }} '
                cd /home/ubuntu/raspberry_net &&
                git checkout main &&
                source venv/bin/activate &&
                git pull origin main &&
                sudo systemctl restart ScriptRun.service
                cd .. &&
                cd django-app &&
                git checkout main &&
                source venv/bin/activate &&
                git pull origin main &&
                sudo systemctl restart ScriptRun.service
              '
