name: Deploy on push dev # Description: This workflow triggers deployment when code is pushed to the staging branch

on:
  push:
    branches:
      - dev  # Trigger: Deploy when pushing changes to the staging branch
jobs:
  Deploy:
    runs-on: ubuntu-latest  # Specify the operating system for the job
    steps:
      - name: Deploy in EC2 and execute commands  # Step: Deploy code and execute commands on the EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Environment variable: SSH private key
          HOSTNAME: ${{ secrets.EC2_IP }}  # Environment variable: Hostname of the EC2 instance
          USERNAME: ${{ secrets.EC2_USERNAME }}  # Environment variable: SSH username

        # SSH into the EC2 instance and execute commands
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key 
          if ssh -o StrictHostKeyChecking=accept-new -i private_key ${USERNAME}@${HOSTNAME} true; then
            set -e

            sudo apt update && \
            
            cd /home/ubuntu/frontend && \
            git stash && \
            git checkout dev && \
            git pull origin dev && \
            npm install && \
            npm run build && \
            
            cd /home/ubuntu/django-app/climatenet && \
            source venv/bin/activate && \
            pip install -r requirements.txt && \
            
            git stash && \
            git checkout dev && \
            git pull origin dev && \
        
            python manage.py collectstatic --noinput && \
  
            sudo systemctl daemon-reload && \
            sudo systemctl restart gunicorn && \
  
            sudo systemctl restart nginx
          else
            echo "Error: Unable to establish SSH connection to ${USERNAME}@${HOSTNAME}"
            exit 1
          fi