name: Deploy to EC2 on Push

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Node.js and npm
#    - name: Setup Node.js
#      uses: actions/setup-node@v2
#      with:
#        node-version: '14'
#
#    # Install npm dependencies and build frontend
#    - name: Build frontend
#      run: |
#        cd /home/ubuntu/workspace/frontend
#        npm install
#        npm run build

    # SSH into EC2 instance and deploy
    - name: SSH into EC2 instance and deploy
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USERNAME }}
        key: ${{ secrets.TEST_SSH_KEY }}
        port: 22
        run: |
          ssh -i ${{ secrets.TEST_SSH_KEY }} ${{ env.TEST_USERNAME }}@${{ env.TEST_HOST }} '
            sudo apt update
            sudo apt install -y python3 python3-pip  # Install Python and pip
            cd /home/ubuntu/workspace/frontend
            npm install
            npm run build
            cd /home/ubuntu/workspace/django-app/climatenet
            git checkout staging && git stash && git pull origin staging'
            source venv/bin/activate
            python manage.py collectstatic --noinput
            gunicorn climatenet.wsgi --bind 0.0.0.0:8000'
