name: Deploy on push staging

on:
  push:
    branches:
      - staging

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy in EC2 and execute commands
        env:
          PRIVATE_KEY: ${{ secrets.TEST_SSH_KEY }}
          HOSTNAME: ${{ secrets.TEST_HOST }}
          USER_NAME: ${{ secrets.TEST_USERNAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh-keyscan ${HOSTNAME} >> ~/.ssh/known_hosts
          ssh -i private_key ${USER_NAME}@${HOSTNAME} '
          cd /home/ubuntu/django-app/climatenet
          
          git checkout staging
          git stash
          git pull origin staging
          
          source venv/bin/activate
          pip install -r requirements.txt
          
          python manage.py collectstatic --noinput
          
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn
          
          sudo systemctl restart nginx'
