name: Deploy on push staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    actions:
      ssh_to_server:
        runs:
          using: "composite"
          steps:
            - name: Set up SSH connection
              env:
                HOSTNAME: ${{ secrets.TEST_HOST }}
                USERNAME: ${{ secrets.TEST_USERNAME }}
                SSH_KEY: ${{ secrets.TEST_SSH_KEY }}
              run: |
                echo "$SSH_KEY" > ssh_key.pem
                chmod 600 ssh_key.pem
                ssh -i ssh_key.pem $USERNAME@$HOSTNAME

    steps:
      - name: Git Checkout and Pull
        run: |
          sudo apt update && \
          cd /home/ubuntu/django-app/climatenet && \
          git checkout staging && git stash && git pull origin staging

      - name: Check Virtual Environment and Install Dependencies
        run:
          cd /home/ubuntu/django-app/climatenet/ && \
          if [ ! -d venv ]; then
            python3 -m venv venv && \
          fi
          source venv/bin/activate && \
          pip install -r requirements.txt

      - name: Restart Nginx
        run:
          sudo systemctl restart nginx

      - name: Collect Static and Restart Gunicorn
        run:
          cd /home/ubuntu/django-app/climatenet/ && \
          python3 manage.py collectstatic --noinput && \
          sudo systemctl daemon-reload && \
          sudo systemctl restart gunicorn.service
