name: Deploy to EC2 on Push

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip  # Install Python and pip
        sudo pip3 install virtualenv  # Install virtualenv (optional)
        cd /home/ubuntu/django-app/climatenet/
        source venv/bin/activate && pip install -r /home/ubuntu/django-app/climatenet/requirements.txt

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USERNAME }}
        key: ${{ secrets.TEST_SSH_KEY }}
        script: |
          cd /home/ubuntu/django-app/climatenet/
          git pull origin staging
          source venv/bin/activate
          gunicorn climatenet.wsgi:application --bind 0.0.0.0:8000
