name: Deploy on push staging

on:
  push:
    branches:
      - staging

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.TEST_SSH_KEY }}
          HOSTNAME: ${{ secrets.TEST_HOSTNAME }}
          USER_NAME: ${{ secrets.TEST_USERNAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}

      - name: Git Checkout and Pull
        run: |
          sudo apt update && \
          cd /home/ubuntu/django-app/climatenet && \
          git checkout staging && git stash && git pull origin staging

      - name: Check Virtual Environment and Install Dependencies
        run: |
          cd /home/ubuntu/django-app/climatenet/ && \
          if [ ! -d venv ]; 
