name: Deploy to EC2 on Push

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Node.js and npm
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install npm dependencies and build frontend
    - name: Build frontend
      run: |
        cd /home/ubuntu/workspace/frontend
        npm install
        npm run build

    # SSH into EC2 instance and deploy
    - name: SSH into EC2 instance and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USERNAME }}
        key: ${{ secrets.TEST_SSH_KEY }}
        port: 22
        script: |
          ssh -i ${{ secrets.TEST_SSH_KEY }} ${{ secrets.TEST_USERNAME }}@${{ secrets.TEST_HOST }} '
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip  # Install Python and pip
            sudo pip3 install virtualenv  # Install virtualenv (optional)
            cd /home/ubuntu/workspace/django-app
            git pull origin staging
            source venv/bin/activate
            python manage.py collectstatic --noinput
            gunicorn climatenet.wsgi:application --bind 0.0.0.0:8000'
