name: Deploy on push staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        env:
          PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
        run: |
          echo "${{ env.TEST_KEY }}" > test_key.pem
          chmod 600 test_key.pem

      - name: Git Checkout and Pull
        env:
          HOSTNAME: ${{ secrets.TEST_HOST }}
          USER_NAME: ${{ secrets.TEST_USERNAME }}
        run: |
          ssh -i test_key.pem ${{ env.TEST_USERNAME }}@${{ env.TEST_HOST }} '
            cd /home/ubuntu/workspace/django-app && \
            git checkout staging && git stash && git pull origin staging'

      - name: Install Dependencies
        env:
          HOSTNAME: ${{ secrets.TEST_HOST }}
          USER_NAME: ${{ secrets.TEST_USERNAME }}
        run: |
          ssh -i test_key.pem ${{ env.TEST_USERNAME }}@${{ env.TEST_HOST }} '
            cd /home/ubuntu/workspace/django-app/climatenet/ && \
            source venv/bin/activate && pip install -r requirements.txt'

      - name: Restart Nginx
        env:
          HOSTNAME: ${{ secrets.TEST_HOST }}
          USER_NAME: ${{ secrets.TEST_USERNAME }}
        run: |
          ssh -i test_key.pem ${{ env.TEST_USERNAME }}@${{ env.TEST_HOST }} '
            sudo systemctl daemon-reload && \
            sudo systemctl restart nginx'

      - name: Collect Static and Restart Gunicorn
        env:
          HOSTNAME: ${{ secrets.TEST_HOST }}
          USER_NAME: ${{ secrets.TEST_USERNAME }}
        run: |
          ssh -i test_key.pem ${{ env.TEST_USERNAME }}@${{ env.TEST_HOSTNAME }} '
            cd /home/ubuntu/workspace/django-app/climatenet/ && \
            echo yes | python3 manage.py collectstatic && \
            sudo systemctl restart gunicorn.service'
